2018-05-09 00:38:56,035 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 82890ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 00:38:56,042 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 82919ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 00:38:56,045 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 82879ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 00:38:56,045 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 82879ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 00:38:56,046 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 82879ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 00:38:56,046 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 82879ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 00:38:56,046 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 82913ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 00:38:56,046 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 82919ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 01:25:31,159 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2735058ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 01:25:31,163 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2735050ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 01:25:31,197 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2735049ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 01:25:31,198 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2735041ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 01:25:31,198 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2735021ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 01:25:31,199 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2735021ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 01:25:31,199 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2735021ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 01:25:31,200 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2735021ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:26:06,024 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634819ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:26:06,024 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634804ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:26:06,024 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634804ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:26:06,024 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634803ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:26:06,024 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634802ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:26:06,024 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634801ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:26:06,024 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634800ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:26:06,025 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634800ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:56:58,902 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832866ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:56:58,902 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832865ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:56:58,904 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832866ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:56:58,904 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832866ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:56:58,904 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832866ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:56:58,904 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1831987ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:56:58,904 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1831972ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 02:56:58,904 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1831971ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 03:27:51,771 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832863ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 03:27:51,771 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832863ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 03:27:51,772 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832863ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 03:27:51,772 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 03:27:51,773 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832853ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 03:27:51,773 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832853ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 03:27:51,773 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832853ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 03:27:51,774 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1832853ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:15:37,661 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6445871ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:15:37,661 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6445870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:15:37,662 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6445870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:15:37,662 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6445871ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:15:37,663 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6445870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:15:37,663 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6445870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:15:37,663 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6445870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:15:37,664 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6445871ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:31:10,433 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 932766ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:31:10,435 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 932758ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:31:10,436 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 932758ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:31:10,437 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 932753ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:31:10,438 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 932753ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:31:10,438 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 932752ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:31:10,439 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 932745ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 05:31:10,439 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 932745ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 06:02:04,279 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1833823ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 06:02:04,288 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1833823ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 06:02:04,288 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1833823ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 06:02:04,289 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1833823ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 06:02:04,289 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1833823ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 06:02:04,290 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1833823ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 06:02:04,291 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1833822ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 06:02:04,291 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 1833822ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 07:02:59,147 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634839ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 07:02:59,149 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634839ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 07:02:59,149 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634838ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 07:02:59,151 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634839ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 07:02:59,151 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634839ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 07:02:59,152 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634839ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 07:02:59,152 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634838ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 07:02:59,160 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 3634838ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 08:50:22,813 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6443646ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 08:50:23,903 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6443645ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 08:50:23,904 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6443645ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 08:50:23,909 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6443644ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 08:50:23,910 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6443643ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 08:50:23,910 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6443643ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 08:50:23,910 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6443634ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 08:50:23,910 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 6443633ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:25:20,472 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2096559ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:25:20,473 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2096558ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:25:20,473 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2096558ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:25:20,474 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2096558ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:25:20,474 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2096558ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:25:20,475 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2096558ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:25:20,475 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2096557ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:25:20,476 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 2096557ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:36:50,693 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 670199ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:36:50,694 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 670199ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:36:50,694 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 670209ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:36:50,695 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 670199ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:36:50,696 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 670199ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:36:50,697 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 670198ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:36:50,697 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 670198ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 09:36:50,699 ERROR 19158 nodejs.ClusterClientNoResponseError: client no response in 670198ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 19158
hostname: Chriss-Laptop.local

2018-05-09 14:44:40,539 ERROR 27621 nodejs.TypeError: Cannot read property 'response' of undefined (uncaughtException throw 1 times on pid:27621)
    at transporter.sendMail (/Users/pengcheng/xiaoji-project/app/utils/mailer.js:49:26)
    at transporter.send.args (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/mailer/index.js:224:21)
    at connection.login.err (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-transport/index.js:281:36)
    at SMTPConnection._actionAUTHComplete (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:1335:20)
    at SMTPConnection._responseActions.push.str (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
    at SMTPConnection._processResponse (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
    at SMTPConnection._onData (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
    at Socket._socket.on.chunk (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)

pid: 27621
hostname: Chriss-Laptop.local

2018-05-09 14:54:37,376 ERROR 27625 nodejs.TypeError: Cannot read property 'response' of undefined (uncaughtException throw 1 times on pid:27625)
    at transporter.sendMail (/Users/pengcheng/xiaoji-project/app/utils/mailer.js:49:26)
    at transporter.send.args (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/mailer/index.js:224:21)
    at connection.login.err (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-transport/index.js:281:36)
    at SMTPConnection._actionAUTHComplete (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:1335:20)
    at SMTPConnection._responseActions.push.str (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
    at SMTPConnection._processResponse (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
    at SMTPConnection._onData (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
    at Socket._socket.on.chunk (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)

pid: 27625
hostname: Chriss-Laptop.local

2018-05-09 14:55:27,889 ERROR 28111 nodejs.TypeError: Cannot read property 'response' of undefined (uncaughtException throw 1 times on pid:28111)
    at transporter.sendMail (/Users/pengcheng/xiaoji-project/app/utils/mailer.js:49:26)
    at transporter.send.args (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/mailer/index.js:224:21)
    at connection.login.err (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-transport/index.js:281:36)
    at SMTPConnection._actionAUTHComplete (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:1335:20)
    at SMTPConnection._responseActions.push.str (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
    at SMTPConnection._processResponse (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
    at SMTPConnection._onData (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
    at Socket._socket.on.chunk (/Users/pengcheng/xiaoji-project/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)

pid: 28111
hostname: Chriss-Laptop.local

2018-05-09 20:17:26,779 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 62793ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 20:17:26,783 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 62775ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 20:17:26,785 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 62733ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 20:17:26,790 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 62762ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 20:17:26,790 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 62733ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 20:17:26,795 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 62762ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 20:17:26,796 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 62733ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 20:17:26,801 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 62697ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:00:29,635 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 2562810ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:00:29,636 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 2562809ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:00:29,645 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 2562810ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:00:29,646 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 2562810ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:00:29,647 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 2562798ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:00:29,648 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 2562809ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:00:29,683 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 2562810ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:00:29,684 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 2562809ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:02:53,380 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 123684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:02:53,380 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 123684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:02:53,381 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 123684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:02:53,381 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 123672ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:02:53,381 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 123673ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:02:53,382 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 123673ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:02:53,382 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 123673ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-09 21:02:53,382 ERROR 34875 nodejs.ClusterClientNoResponseError: client no response in 123673ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 34875
hostname: Chriss-Laptop.local

2018-05-11 05:25:48,602 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6427622ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 05:25:48,603 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6427561ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 05:25:48,603 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6427550ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 05:25:48,603 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6427510ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 05:25:48,603 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6427490ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 05:25:48,604 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6427524ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 05:25:48,604 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6427455ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 05:25:48,604 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6427443ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:13:30,104 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6461496ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:13:30,104 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6461496ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:13:30,106 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6461496ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:13:30,106 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6461496ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:13:30,106 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6461495ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:13:30,107 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6461495ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:13:30,107 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6461495ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:13:30,108 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6461495ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:44:03,728 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 1833615ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:44:03,744 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 1833615ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:44:03,744 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 1833615ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:44:03,745 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 1833615ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:44:03,746 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 1833614ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:44:03,746 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 1833614ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:44:03,747 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 1833614ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 07:44:03,751 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 1833614ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 09:36:18,172 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6714411ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 09:36:18,187 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6714411ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 09:36:18,187 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6714411ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 09:36:18,188 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6714411ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 09:36:18,188 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6714411ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 09:36:18,189 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6714408ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 09:36:18,190 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6714408ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 09:36:18,190 ERROR 56287 nodejs.ClusterClientNoResponseError: client no response in 6714407ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 56287
hostname: Chriss-Laptop.local

2018-05-11 19:43:39,288 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 406990ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 19:43:39,289 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 406953ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 19:43:39,392 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 406915ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 19:43:39,392 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 406916ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 19:43:39,392 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 406863ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 19:43:39,393 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 406809ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 19:43:39,394 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 406843ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 19:43:39,394 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 406843ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:29:27,438 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 218090ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:29:27,465 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 218089ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:29:27,465 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 218085ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:29:27,466 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 218089ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:29:27,467 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 218077ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:29:27,467 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 218090ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:29:27,468 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 218134ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:29:27,468 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 218089ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:32:05,248 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 157772ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:32:05,249 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 157772ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:32:05,249 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 157771ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:32:05,251 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 157770ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:32:05,251 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 157770ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:32:05,251 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 157770ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:32:05,251 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 157769ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:32:05,251 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 157768ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:45:38,094 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 792829ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:45:38,095 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 792828ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:45:38,096 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 792830ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:45:38,096 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 792829ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:45:38,096 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 792829ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:45:38,096 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 792830ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:45:38,097 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 792829ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 20:45:38,097 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 792830ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 21:26:24,974 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 2426872ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 21:26:24,974 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 2426872ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 21:26:24,974 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 2426872ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 21:26:24,975 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 2426870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 21:26:24,975 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 2426871ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 21:26:24,975 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 2426870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 21:26:24,975 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 2426871ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 21:26:24,976 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 2426869ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:14:03,862 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438857ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:14:03,886 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:14:03,886 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:14:03,887 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:14:03,888 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438864ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:14:03,888 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438852ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:14:03,890 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438852ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:29:35,384 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 931484ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:29:35,417 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 931484ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:29:35,417 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 931483ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:29:35,418 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 931483ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:29:35,418 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 931481ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:29:35,419 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 931479ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-11 23:29:35,419 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 931479ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 00:45:14,081 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 4537830ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 00:45:14,087 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 4537789ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 00:45:14,097 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 4537789ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 00:45:14,098 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 4537788ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 00:45:14,098 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 4537788ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 00:45:14,125 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 4537787ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 00:45:14,125 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 4537785ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 00:45:14,126 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 4537784ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 02:32:52,934 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438797ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 02:32:52,935 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438796ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 02:32:52,935 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438797ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 02:32:52,935 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438797ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 02:32:52,936 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438797ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 02:32:52,936 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438797ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 02:32:52,936 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438797ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 02:32:52,936 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6438797ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 04:20:33,474 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6460533ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 04:20:33,476 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6460532ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 04:20:33,477 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6460532ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 04:20:33,478 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6460532ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 04:20:33,478 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6460532ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 04:20:33,479 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6460532ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 04:20:33,482 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6460531ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 04:20:33,482 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 6460531ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 06:38:25,526 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 8272035ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 06:38:25,526 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 8272035ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 06:38:25,526 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 8272034ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 06:38:25,542 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 8272034ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 06:38:25,542 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 8272033ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 06:38:25,543 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 8272033ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 06:38:25,543 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 8272032ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 06:38:25,543 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 8272032ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:09:22,324 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 5436765ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:09:22,324 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 5436765ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:09:22,325 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 5436766ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:09:22,325 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 5436766ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:09:22,326 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 5436765ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:09:22,326 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 5436766ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:09:22,327 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 5436766ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:09:22,327 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 5436765ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:26:36,243 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 1013914ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:26:36,244 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 1013914ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:26:36,244 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 1013914ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:26:36,245 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 1013913ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:26:36,245 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 1013913ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:26:36,245 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 1013913ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:26:36,246 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 1013913ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 08:26:36,246 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 1013913ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 09:23:19,342 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 3403092ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 09:23:19,342 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 3403092ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 09:23:19,342 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 3403092ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 09:23:19,343 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 3403091ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 09:23:19,343 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 3403091ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 09:23:19,343 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 3403090ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 09:23:19,344 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 3403090ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

2018-05-12 09:23:19,344 ERROR 63738 nodejs.ClusterClientNoResponseError: client no response in 3403090ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/pengcheng/xiaoji-project/node_modules/cluster-client/lib/leader.js:73:23)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
name: 'ClusterClientNoResponseError'
pid: 63738
hostname: Chriss-Laptop.local

